//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareLibray
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShareFile", Namespace="http://schemas.datacontract.org/2004/07/ShareLibray")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class ShareFile : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int UserIDField;
        
        private byte[] fileField;
        
        private int nField;
        
        private object[] sharesField;
        
        private int tField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int n
        {
            get
            {
                return this.nField;
            }
            set
            {
                this.nField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] shares
        {
            get
            {
                return this.sharesField;
            }
            set
            {
                this.sharesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int t
        {
            get
            {
                return this.tField;
            }
            set
            {
                this.tField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IShareStorageService")]
public interface IShareStorageService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareStorageService/getShares", ReplyAction="http://tempuri.org/IShareStorageService/getSharesResponse")]
    ShareLibray.ShareFile getShares(ShareLibray.ShareFile file, int UserID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareStorageService/getShares", ReplyAction="http://tempuri.org/IShareStorageService/getSharesResponse")]
    System.Threading.Tasks.Task<ShareLibray.ShareFile> getSharesAsync(ShareLibray.ShareFile file, int UserID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareStorageService/uploaedShares", ReplyAction="http://tempuri.org/IShareStorageService/uploaedSharesResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ShareLibray.ShareFile))]
    void uploaedShares(int UserID, int FileID, object[] shares);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShareStorageService/uploaedShares", ReplyAction="http://tempuri.org/IShareStorageService/uploaedSharesResponse")]
    System.Threading.Tasks.Task uploaedSharesAsync(int UserID, int FileID, object[] shares);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IShareStorageServiceChannel : IShareStorageService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShareStorageServiceClient : System.ServiceModel.ClientBase<IShareStorageService>, IShareStorageService
{
    
    public ShareStorageServiceClient()
    {
    }
    
    public ShareStorageServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShareStorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShareStorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShareStorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ShareLibray.ShareFile getShares(ShareLibray.ShareFile file, int UserID)
    {
        return base.Channel.getShares(file, UserID);
    }
    
    public System.Threading.Tasks.Task<ShareLibray.ShareFile> getSharesAsync(ShareLibray.ShareFile file, int UserID)
    {
        return base.Channel.getSharesAsync(file, UserID);
    }
    
    public void uploaedShares(int UserID, int FileID, object[] shares)
    {
        base.Channel.uploaedShares(UserID, FileID, shares);
    }
    
    public System.Threading.Tasks.Task uploaedSharesAsync(int UserID, int FileID, object[] shares)
    {
        return base.Channel.uploaedSharesAsync(UserID, FileID, shares);
    }
}
